---
- hosts: web
  remote_user: root
  become: yes
  become_method: su

  tasks:
  - name: Install Apache
    yum: pkg=httpd state=latest
  - name: Enable Apache on System Boot
    service: name=httpd enabled=yes
  - name: Copying the demo file
    template: src=/opt/ansible/static/index.html dest=/var/www/html
              owner=apache group=apache mode=0644
    notify:
    - start apache
    - setup firewalld
    - reload firewalld

  handlers:
    - name: start apache
      service: name=httpd state=started
    - name: setup firewalld
      firewalld:
        service: http
        permanent: true
        state: enabled
    - name: reload firewalld
      service: name=firewalld state=restarted
